version: '3'

networks:
  default:
    external:
      name: proxy_net 
      
services:
  vaultwarden:
    image: vaultwarden/server
    container_name: password
    restart: unless-stopped
    volumes:
      - ./vaultwarden:/data
    environment:
      - VIRTUAL_HOST=password.${MYDOMAIN}
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${ADM_PW}
