version: "3.9"

services:
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    volumes:
      - "./lldap:/data"
    environment:
      - TZ=${TZ}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_BASE_DN=${BASE_DN}
      - LLDAP_ADMIN_USERNAME=${LLDAP_ADMIN_USERNAME}
      - LLDAP_ADMIN_PASSWORD=${LLDAP_ADMIN_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ldap.rule=Host(`lldap.${MYDOMAIN}`)
      - traefik.http.services.labels.loadbalancer.server.port=17170
    networks:
      - proxy
      - auth

  tinyauth:
    image: ghcr.io/jason-k/tinyauth:latest
    container_name: tinyauth
    volumes:
      - ./tinyauth:/config
    networks:
      - proxy
      - auth
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tinyauth.rule=Host(`tinyauth.${MYDOMAIN}`)'
      - 'traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik' 
      - 'traefik.http.middlewares.tinyauth.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TINYAUTH_LDAP_ADDRESS=ldap://my-lldap-server:3890
      - TINYAUTH_LDAP_BINDDN=uid=tinyauth,ou=people,${BASE_DN}
      - TINYAUTH_LDAP_BINDPASSWORD=${LLDAP_TINYAUTH_PASSWORD}
      - TINYAUTH_LDAP_BASEDN=dc=${BASE_DN}
      - TINYAUTH_LDAP_SEARCHFILTER=(uid=%s)
      - TINYAUTH_LDAP_INSECURE=true
      
networks:
  proxy:
    external: true
  auth:
    name: auth
