version: "3.9"

services:
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    volumes:
      - "./lldap:/data"
    environment:
      - TZ=${TZ}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_BASE_DN=${BASE_DN}
      - LLDAP_ADMIN_USERNAME=${LLDAP_ADMIN_USERNAME}
      - LLDAP_ADMIN_PASSWORD=${LLDAP_ADMIN_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ldap.rule=Host(`lldap.${MYDOMAIN}`)
      - traefik.http.services.labels.loadbalancer.server.port=17170
    networks:
      - proxy
      - auth
    ports:
      - "17170:17170"

  authelia:
    image: authelia/authelia
    container_name: authelia
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config=/config/cookies.yml'
      - '--config=/config/access_rules.yml'
    volumes:
      - ./authelia:/config
    networks:
      - proxy
      - auth
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.${MYDOMAIN}`)'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth' 
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  
    restart: unless-stopped
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD=${LLDAP_AUTHELIA_PASSWORD}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN=${BASE_DN}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_PW_RESET_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}

      

networks:
  proxy:
    external: true
  auth:
    name: auth