services:
  # IDSTower Web Management UI
  idstower:
    image: idstower/idstower:latest
    container_name: idstower
    environment:
      - ADMIN_USER=idsadmin
      - ADMIN_PASSWORD=blippboppbot # Change this immediately
      - DB_TYPE=sqlite3 # Using built-in SQLite for easy setup
    labels:
      - traefik.enable=true
      - traefik.http.routers.idstower.rule=Host(`idstower.${MYDOMAIN}`)
      - traefik.http.services.idstower.loadbalancer.server.port=8000
    volumes:
      - ./idstower:/var/lib/idstower
    restart: unless-stopped
    networks:
      - proxy

  # Suricata IDS Engine
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "host" # Crucial to sniff host/docker interface traffic
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./suricata/logs:/var/log/suricata
      - ./suricata/config:/etc/suricata
    command: -i enp4s0 # Replace with eth0, docker0, etc.
    restart: unless-stopped
    depends_on:
      - idstower

networks:
  proxy:
    external: true
