services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      LAPI_LISTEN_ADDR: 0.0.0.0
      TRUSTED_IPS: 172.19.0.1
      COLLECTIONS: >-
        crowdsecurity/traefik
        crowdsecurity/http-cve
        crowdsecurity/sshd
        crowdsecurity/linux
        crowdsecurity/nextcloud
        crowdsecurity/whitelist-good-actors
        crowdsecurity/suricata
      PARSERS: "crowdsecurity/geoip-enrich"
    volumes:
      - ./crowdsec/config:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data/
      - suricata-tmpfs-logs:/var/log/suricata:ro
      - ${TRAEFIK_LOGS_DIR:-./../proxy/traefik/logs}:/var/log/traefik:ro
      - ${SSH_LOGS_DIR:-/var/log/auth.log}:/var/log/auth.log:ro
    ports:
      - "8080:8080"  # Expose LAPI to host
    
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - suricata-tmpfs-logs:/var/log/suricata
      - ./suricata/rules:/var/lib/suricata
      - ./suricata/config:/etc/suricata
    restart: unless-stopped
    command: >
      -i ${MONITOR_IFACE:-enp4s0}
      --set outputs.1.eve-log.limit=400mb

volumes:
  # Allocates a maximum of 50 Megabytes in host system memory
  suricata-tmpfs-logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=500M,uid=1000,gid=1000"
