version: '3.3'
services:
###################################################################################
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    networks:
      - proxy_net
    volumes:
      - ./syncthing:/config
      - ./data:/data
    environment:
      - VIRTUAL_HOST=syncthing.${MYDOMAIN}
      - VIRTUAL_PORT=8384
      - TZ=${TZ}
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped

###################################################################################
  filebrowser:
    image: hurlenko/filebrowser
    networks:
      - proxy_net
    volumes:
      - ./filebrowser:/config 
      - ./data:/data
    environment:
      - FB_BASEURL=/filebrowser
      - VIRTUAL_HOST=filebrowser.${MYDOMAIN}
      - VIRTUAL_PORT=8080
    restart: always

###################################################################################
  db:
    image: mariadb:10.5
    restart: always
    networks:
      - dbnet
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./photoview/db:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:2
    restart: always
    networks:
      - proxy_net
      - dbnet
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=photoview.${MYDOMAIN}
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:${MYSQL_PASSWORD}@tcp(db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      
      # Optional: To enable map related features, you need to create a mapbox token.
      # A token can be generated for free here https://account.mapbox.com/access-tokens/
      # It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.
      - MAPBOX_TOKEN=${MAPBOX_KEY}

    volumes:
      - ./photoview/cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - ./data:/data:ro

###################################################################################
networks:
  proxy_net:
    external: true
  dbnet:

