version: '3'
     
services:
  wiki:
    image: linbreux/wikmd:latest
    container_name: wiki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`wiki.${MYDOMAIN}`)"
      - "traefik.http.routers.wiki.middlewares=authelia@docker"
      - "traefik.http.services.wiki.loadbalancer.server.port=5000" 
    networks:
      - proxy

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./wikmd:/wiki
    restart: unless-stopped

networks:
  proxy:
    external: true
