version: '3'

networks:
  default:
    external:
      name: proxy_net 
      
services:
  wiki:
    image: linbreux/wikmd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./wiki:/wiki
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`wiki.${MYDOMAIN}`)
      - traefik.http.services.labels.loadbalancer.server.port=5000

    restart: unless-stopped
