version: "3.9"

services:
  ldap:
    image: lldap/lldap:stable
    #ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      #- "17170:17170"
    volumes:
      # - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      - "./lldap:/data"
    environment:
      - UID=1000
      - GID=1000
      - TZ=${TZ}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=dc=1a,dc=nu
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
      # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
    labels:
      - traefik.enable=true
      - traefik.http.routers.ldap.rule=Host(`ldap.${MYDOMAIN}`)
      - traefik.http.services.labels.loadbalancer.server.port=17170
    networks:
      - proxy
      - ldap

networks:
  proxy:
    external: true
  ldap:
    name: ldap