sources:
  traefik:
    type: file
    path: /var/log/traefik/access.log
    labels:
      type: traefik

  ssh:
    type: file
    path: /var/log/auth.log
    labels:
      type: syslog

  cockpit:
    type: file
    path: /var/log/cockpit/
    labels:
      type: cockpitsources:
  traefik:
    type: file
    path: /var/log/traefik/access.log
    labels:
      type: traefik
